name: CppInterOp-wasm
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - emscripten-abi==4.0.9
  - nlohmann_json
  - nlohmann_json-abi
  - xeus-lite
  - xeus
  - cpp-argparse
  - pugixml
  - doctest
