
name: 'ROOT Docs 6.32'

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 12 * * *'

  workflow_dispatch:
    inputs:
      incremental:
        description: 'Do incremental build'
        type: boolean
        required: true
        default: true
      # docu_input: # opportunity: overwrite makeinput.sh with these args
      #   description: Folders to build documentation for. All folders are built if empty.
      #   type: string
      #   default: ""
      #   required: false

jobs:
  run_nightlies:
    uses: root-project/root/.github/workflows/root-docs-ci.yml@v6-32-00-patches
    secrets: inherit
